import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // ── MITRA Glass palette ─────────────────
        primary: {
          DEFAULT: '#7C3AED',
          light: '#A78BFA',
          dark: '#5B21B6',
          50: '#F5F3FF',
          100: '#EDE9FE',
          200: '#DDD6FE',
          500: '#7C3AED',
          600: '#6D28D9',
          700: '#5B21B6',
          900: '#2E1065',
        },
        teal: {
          DEFAULT: '#14B8A6',
          light: '#CCFBF1',
          50: '#F0FDFA',
          500: '#14B8A6',
          600: '#0D9488',
        },
        rose: {
          DEFAULT: '#F43F5E',
          light: '#FFF1F2',
          50: '#FFF1F2',
          500: '#F43F5E',
          600: '#E11D48',
        },
        amber: {
          DEFAULT: '#F59E0B',
          light: '#FEF3C7',
          50: '#FFFBEB',
          500: '#F59E0B',
          600: '#D97706',
        },
        surface: {
          DEFAULT: '#FAFBFE',
          muted: '#F1F3F9',
          elevated: '#FFFFFF',
        },
        glass: {
          DEFAULT: 'rgba(255,255,255,0.72)',
          strong: 'rgba(255,255,255,0.88)',
          border: 'rgba(255,255,255,0.3)',
          subtle: 'rgba(255,255,255,0.5)',
        },
        texto: { // backward compat aliases
          DEFAULT: '#1E1B4B',
          soft: '#6B7280',
          muted: '#9CA3AF',
        },
        success: { DEFAULT: '#10B981', light: '#D1FAE5' },
        error: { DEFAULT: '#EF4444', light: '#FEE2E2' },
        info: { DEFAULT: '#6366F1', light: '#E0E7FF' },
        warning: { DEFAULT: '#F59E0B', light: '#FEF3C7' },
        // ── Backward compat (old names → new values) ──
        coral: '#7C3AED',
        'coral-light': '#F5F3FF',
        rosa: '#F43F5E',
        'rosa-light': '#FFF1F2',
        menta: '#14B8A6',
        'menta-light': '#F0FDFA',
        azul: '#6366F1',
        'azul-light': '#E0E7FF',
        amarelo: '#F59E0B',
        'amarelo-light': '#FEF3C7',
        creme: '#FAFBFE',
        'creme-dark': '#F1F3F9',
        branco: '#FFFFFF',
        footer: '#1E1B4B',
        erro: '#EF4444',
        'erro-light': '#FEE2E2',
      },
      fontFamily: {
        headline: ['var(--font-satoshi)', 'Satoshi', 'system-ui', 'sans-serif'],
        body: ['var(--font-inter)', 'Inter', 'system-ui', 'sans-serif'],
        label: ['var(--font-satoshi)', 'Satoshi', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '1.25rem',
        xl: '1.5rem',
        '2xl': '2rem',
        full: '9999px',
      },
      boxShadow: {
        'glass': '0 8px 32px rgba(124,58,237,0.06)',
        'glass-hover': '0 12px 40px rgba(124,58,237,0.12)',
        'glass-glow': '0 0 20px rgba(124,58,237,0.15)',
        'card': '0 2px 16px rgba(30,27,75,0.06)',
        'card-hover': '0 8px 30px rgba(30,27,75,0.1)',
        'modal': '0 20px 60px rgba(30,27,75,0.15)',
        'nav': '0 1px 0 rgba(30,27,75,0.06)',
        'ambient': '0 4px 48px rgba(30,27,75,0.06)',
        'glow-primary': '0 0 20px rgba(124,58,237,0.3)',
        'glow-teal': '0 0 20px rgba(20,184,166,0.3)',
        'glow-rose': '0 0 20px rgba(244,63,94,0.3)',
        'glow-amber': '0 0 20px rgba(245,158,11,0.3)',
        'inner-glow': 'inset 0 1px 0 rgba(255,255,255,0.5)',
      },
      backdropBlur: {
        xs: '4px',
        glass: '16px',
        heavy: '24px',
      },
      animation: {
        'fade-in': 'fadeIn 0.2s ease-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'slide-down': 'slideDown 0.3s ease-out',
        'scale-in': 'scaleIn 0.2s ease-out',
        'shimmer': 'shimmer 1.5s ease-in-out infinite',
        'slide-in-right': 'slideInRight 0.3s ease-out',
        'bounce-down': 'bounceDown 2s ease-in-out infinite',
        'reveal-up': 'revealUp 0.6s ease-out forwards',
        'wiggle': 'wiggle 0.3s ease-in-out',
        'float': 'float 7s ease-in-out infinite',
        'float-slow': 'floatSlow 9s ease-in-out infinite',
        'squishy': 'squishy 0.15s ease-out',
        'bounce-in': 'bounceIn 0.4s var(--ease-bounce) forwards',
        'fade-slide-up': 'fadeSlideUp 0.5s ease-out forwards',
        'pulse-badge': 'pulseBadge 0.6s ease-in-out',
        'glow-pulse': 'glowPulse 2s ease-in-out infinite',
        'tab-slide': 'tabSlide 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
        'glass-shimmer': 'glassShimmer 2s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: { from: { opacity: '0' }, to: { opacity: '1' } },
        slideUp: {
          from: { opacity: '0', transform: 'translateY(8px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        slideDown: {
          from: { opacity: '0', transform: 'translateY(-8px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        scaleIn: {
          from: { opacity: '0', transform: 'scale(0.95)' },
          to: { opacity: '1', transform: 'scale(1)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        slideInRight: {
          from: { opacity: '0', transform: 'translateX(100%)' },
          to: { opacity: '1', transform: 'translateX(0)' },
        },
        bounceDown: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(8px)' },
        },
        revealUp: {
          from: { opacity: '0', transform: 'translateY(24px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        wiggle: {
          '0%, 100%': { transform: 'rotate(0deg)' },
          '25%': { transform: 'rotate(-3deg)' },
          '75%': { transform: 'rotate(3deg)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px) scale(1)' },
          '50%': { transform: 'translateY(-14px) scale(1.03)' },
        },
        floatSlow: {
          '0%, 100%': { transform: 'translateY(0px) rotate(0deg)' },
          '50%': { transform: 'translateY(-10px) rotate(3deg)' },
        },
        squishy: {
          '0%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(0.92)' },
          '100%': { transform: 'scale(1)' },
        },
        bounceIn: {
          '0%': { transform: 'scale(0)', opacity: '0' },
          '50%': { transform: 'scale(1.08)', opacity: '1' },
          '75%': { transform: 'scale(0.96)' },
          '100%': { transform: 'scale(1)' },
        },
        fadeSlideUp: {
          from: { opacity: '0', transform: 'translateY(20px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        pulseBadge: {
          '0%, 100%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.25)' },
        },
        glowPulse: {
          '0%, 100%': { boxShadow: '0 0 15px rgba(124,58,237,0.15)' },
          '50%': { boxShadow: '0 0 30px rgba(124,58,237,0.3)' },
        },
        tabSlide: {
          from: { opacity: '0.5' },
          to: { opacity: '1' },
        },
        glassShimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
      },
    },
  },
  plugins: [],
};

export default config;
